### PR TITLE
Add power connector 3D file

### PR DESCRIPTION
**Pull request by LeftistTachyon**
Add in the 3D model file for the power connectors + create a new library folder for the power connectors
> [!NOTE]
> The `KICAD_ROBOMASTERS_3DMODEL_DIR` has been changed to point to the `KiCad_Library` directory as a result.

### CODE REVIEW

**Comment by Lakshay983** [comment]
Can u make this not in the ICs.pretty folder? Make like a Connectors.pretty folder

**Comment by LeftistTachyon** [comment]
subjective no change

**Comment by LeftistTachyon** [comment]
> Can u make this not in the ICs.pretty folder? Make like a Connectors.pretty folder

Done

**Review by Lakshay983 — APPROVED** [review]
LGTM

**Pull request merged**
